## Project
name: tasty_bytes
version: "1.0"
config-version: 2
profile: tasty_bytes

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  tasty_bytes:
    staging:
      +materialized: view
      +schema: staging   # 这里加上 schema
    marts:
      +materialized: table
      +schema: marts     # 这里加上 schema
