tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: XIYJ_DB
      schema: DBT
      warehouse: XIYJ_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: XIYJ_DB
      schema: DBT
      warehouse: XIYJ_WH